
import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
async function api(p,o={},t=""){let h=new Headers(o.headers||{});if(t)h.set("Authorization","Bearer "+t);if(o.body&&!(o.body instanceof FormData))h.set("Content-Type","application/json");let r=await fetch(API+p,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||"Request failed");return d}
function Auth({done}){let[m,setM]=useState("login"),[e,setE]=useState(""),[p,setP]=useState(""),[n,setN]=useState(""),[x,setX]=useState("");async function go(a){a.preventDefault();try{let d=await api(m==="login"?"/api/auth/login":"/api/auth/register",{method:"POST",body:JSON.stringify({email:e,password:p,name:n})});localStorage.token=d.access_token;done(d.user)}catch(a){setX(a.message)}}return <div className="auth"><form className="card" onSubmit={go}><div className="logo">NASSER <i>PDF</i></div><small>V3 SAAS</small><h1>{m==="login"?"Welcome back":"Create account"}</h1>{m==="register"&&<input placeholder="Name" value={n} onChange={a=>setN(a.target.value)} required/>}<input type="email" placeholder="Email" value={e} onChange={a=>setE(a.target.value)} required/><input type="password" minLength="8" placeholder="Password" value={p} onChange={a=>setP(a.target.value)} required/>{x&&<div className="error">{x}</div>}<button>Continue</button><a onClick={()=>setM(m==="login"?"register":"login")}>{m==="login"?"Create account":"Sign in"}</a></form></div>}
function App(){let[u,setU]=useState(null),[d,setD]=useState(null),[files,setFiles]=useState([]),[tab,setTab]=useState("dashboard"),t=localStorage.token;async function load(){setD(await api("/api/dashboard",{},t));setFiles(await api("/api/documents",{},t))}useEffect(()=>{if(t)api("/api/auth/me",{},t).then(setU).catch(()=>localStorage.removeItem("token"))},[]);useEffect(()=>{if(u)load()},[u]);if(!u)return <Auth done={setU}/>;if(!d)return <div className="loading">Loading…</div>;async function up(e){let f=e.target.files[0];if(!f)return;let q=new FormData;q.append("file",f);await api("/api/documents/upload",{method:"POST",body:q},t);load()}async function del(id){await api("/api/documents/"+id,{method:"DELETE"},t);load()}function List({items}){return <div>{items.length?items.map(f=><div className="file" key={f.id}><b>{f.name}</b><small>{(f.size_bytes/1048576).toFixed(2)} MB · {f.operation}</small><button onClick={async()=>{let r=await fetch(API+"/api/documents/"+f.id+"/download",{headers:{Authorization:"Bearer "+t}}),b=await r.blob(),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=f.name;a.click()}}>Download</button><button onClick={()=>del(f.id)}>Delete</button></div>):<p>No documents yet.</p>}</div>}return <div><header><div className="logo">NASSER <i>PDF</i></div><span>{u.email}<button onClick={()=>{localStorage.removeItem("token");setU(null)}}>Logout</button></span></header><div className="layout"><nav>{["dashboard","documents","history","plan"].map(x=><button onClick={()=>setTab(x)}>{x}</button>)}<label className="upload">＋ Upload PDF<input type="file" accept=".pdf" onChange={up}/></label></nav><main>{tab==="dashboard"&&<><h1>Welcome back{u.name?", "+u.name:""} 👋</h1><div className="stats"><div><b>{d.stats.documents}</b><small>Documents</small></div><div><b>{d.stats.operations}/{d.stats.operations_limit}</b><small>Operations</small></div><div><b>{u.plan.toUpperCase()}</b><small>Plan</small></div></div><section><h3>Recent documents</h3><List items={d.recent}/></section></>}{tab==="documents"&&<section><h2>Documents</h2><List items={files}/></section>}{tab==="history"&&<section><h2>History</h2><List items={files}/></section>}{tab==="plan"&&<div className="plans"><section><h2>Free</h2><p>10 operations/month</p><p>100 MB storage</p><button onClick={()=>api("/api/billing/plan",{method:"POST",body:JSON.stringify({plan:"free"})},t).then(load)}>Choose Free</button></section><section><h2>Pro — $9</h2><p>1,000 operations/month</p><p>10 GB storage</p><button onClick={()=>api("/api/billing/plan",{method:"POST",body:JSON.stringify({plan:"pro"})},t).then(load)}>Choose Pro</button></section></div>}</main></div></div>}
createRoot(document.getElementById("root")).render(<App/>);
